# coding: utf-8

"""
    OSCHINA IT资讯APP后端API

    基于FastAPI开发的OSCHINA资讯代理后端API 1. 集成OSCHINA OAuth2.0授权登录 2. 后端代理所有OSCHINA OpenAPI请求，客户端无直接调用 3. 支持新闻/博客列表/详情、全局搜索 4. 自定义用户收藏功能（新闻/博客收藏管理） 5. 自定义数据模型适配Flutter客户端展示需求 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501
from urllib.parse import urlencode, parse_qs, unquote

from fastapi import FastAPI, Request, Depends
from starlette.datastructures import QueryParams
from starlette.middleware.base import BaseHTTPMiddleware

from openapi_server.apis.default_api import router as DefaultApiRouter
from openapi_server.database.database import engine, Base


class StrictPathParamConverterMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # 提取路径参数并尝试转换为int
        path_params = request.scope.get("path_params", {})
        modified_params = {}
        for key, value in path_params.items():
            # 判断是否可能需要转为int（可根据实际情况扩展）
            if value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
                modified_params[key] = int(value)
            else:
                modified_params[key] = value

        # 更新路径参数
        request.scope["path_params"] = modified_params

        response = await call_next(request)
        return response


class StrictQueryParamConverterMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # 解析查询参数
        query_params = parse_qs(unquote(request.scope["query_string"].decode("utf-8")))
        modified_params = {}

        for key, values in query_params.items():
            modified_values = []
            for value in values:
                # 尝试转换为int
                if value.isdigit() or (value.startswith('-') and value[1:].isdigit()):
                    modified_values.append(str(int(value)))  # 转换后转回字符串，FastAPI会再处理
                else:
                    modified_values.append(value)
            modified_params[key] = modified_values

        # 重新编码查询字符串
        params = QueryParams(modified_params)
        request._query_params = params

        response = await call_next(request)
        return response

Base.metadata.create_all(bind=engine)
app = FastAPI(
    title="OSCHINA IT资讯APP后端API",
    description="基于FastAPI开发的OSCHINA资讯代理后端API 1. 集成OSCHINA OAuth2.0授权登录 2. 后端代理所有OSCHINA OpenAPI请求，客户端无直接调用 3. 支持新闻/博客列表/详情、全局搜索 4. 自定义用户收藏功能（新闻/博客收藏管理） 5. 自定义数据模型适配Flutter客户端展示需求 ",
    version="1.0.0",
)
# app.add_middleware(StrictQueryParamConverterMiddleware)
# app.add_middleware(StrictPathParamConverterMiddleware)

app.include_router(DefaultApiRouter)
